require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5.3

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/InstanceVariable:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false
