inherit_gem:
  rubocop-govuk:
    - config/default.yml

AllCops:
  TargetRubyVersion: 2.6.6
  Exclude:
    - 'vendor/**/*'

Layout/AccessModifierIndentation:
  Enabled: false

Style/StderrPuts:
  Enabled: false
