branches:
  only: [master]
language: ruby
rvm:
 - 2.6.6
before_install: # somehow travis isn't coming with bundler preinstalled any more?!
  - gem install bundler -v '>= 2' || true
script:
  - bundle exec rspec
  - bundle exec rubocop
notifications:
  email: false
