language: ruby
rvm:
 - 2.5.3
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
script:
  - bundle exec rspec
  - bundle exec rubocop
notifications:
  email: false
